
create table if not exists public.users (
 id bigint generated by default as identity primary key,
 name text not null,
 email text unique not null,
 password text not null,
 role text not null,
 portfolio text default '',
 phone text default '',
 class_name text default '',
 branch text default '',
 is_active boolean default true,
 created_at timestamptz default now()
);

create table if not exists public.teams (
 id bigint generated by default as identity primary key,
 slug text unique not null,
 name text not null,
 lead_user_id bigint references public.users(id),
 faculty_coordinator_id bigint references public.users(id),
 description text default '',
 source_page integer,
 source_note text default '',
 created_at timestamptz default now()
);

create table if not exists public.team_budgets (
 id bigint generated by default as identity primary key,
 team_id bigint not null unique references public.teams(id) on delete cascade,
 fiscal_year text default '2026-27',
 allocated_amount numeric default 0,
 notes text default '',
 updated_by bigint references public.users(id),
 updated_at timestamptz default now()
);

create table if not exists public.budget_transactions (
 id bigint generated by default as identity primary key,
 team_id bigint not null references public.teams(id) on delete cascade,
 title text not null,
 amount numeric not null,
 transaction_type text default 'Expense',
 status text default 'Approved',
 reference text default '',
 created_by bigint references public.users(id),
 created_at timestamptz default now()
);

create table if not exists public.team_members (
 id bigint generated by default as identity primary key,
 team_id bigint not null references public.teams(id) on delete cascade,
 user_id bigint not null references public.users(id) on delete cascade,
 position text default 'Committee Member',
 is_lead boolean default false,
 joined_at timestamptz default now(),
 unique(team_id,user_id)
);

alter table public.tasks add column if not exists description text default '';
alter table public.tasks add column if not exists category text default 'General';
alter table public.tasks add column if not exists assigned_to bigint;
alter table public.tasks add column if not exists assigned_by bigint;
alter table public.tasks add column if not exists team_id bigint;
alter table public.tasks add column if not exists due_date text default '';
alter table public.tasks add column if not exists due_time text default '';
alter table public.tasks add column if not exists updated_at timestamptz default now();
alter table public.tasks add column if not exists comments text default '';

create table if not exists public.events (
 id bigint generated by default as identity primary key,
 title text not null,
 date text not null,
 start_time text default '',
 end_time text default '',
 location text default '',
 event_type text default 'General',
 priority text default 'Normal',
 description text default '',
 organizer text default '',
 capacity integer default 0,
 team_id bigint references public.teams(id),
 status text default 'Proposed',
 budget_allocated numeric default 0,
 created_by bigint references public.users(id),
 created_at timestamptz default now()
);

create table if not exists public.meetings (
 id bigint generated by default as identity primary key,
 title text not null,
 date text not null,
 time text default '',
 location text default '',
 meeting_type text default 'Regular',
 agenda text default '',
 minutes text default '',
 action_items text default '',
 team_id bigint references public.teams(id),
 created_by bigint references public.users(id),
 status text default 'Scheduled',
 completed_at timestamptz,
 created_at timestamptz default now()
);

alter table public.meetings add column if not exists status text default 'Scheduled';
alter table public.meetings add column if not exists completed_at timestamptz;

create table if not exists public.finances (
 id bigint generated by default as identity primary key,
 title text not null,
 amount numeric not null,
 type text default 'Operations',
 priority text default 'Normal',
 status text default 'Pending',
 requested_by bigint references public.users(id),
 approved_by bigint references public.users(id),
 team_id bigint references public.teams(id),
 vendor text default '',
 justification text default '',
 receipt_url text default '',
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);

create table if not exists public.grievances (
 id bigint generated by default as identity primary key,
 subject text not null,
 description text not null,
 category text default 'General',
 department text default '',
 contact_preference text default 'Portal notification',
 is_anonymous boolean default false,
 follow_up_allowed boolean default true,
 priority text default 'Normal',
 status text default 'Open',
 created_by bigint references public.users(id),
 assigned_to bigint references public.users(id),
 resolution_notes text default '',
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);

create table if not exists public.announcements (
 id bigint generated by default as identity primary key,
 title text not null,
 content text not null,
 audience text default 'Council',
 team_id bigint references public.teams(id),
 created_by bigint references public.users(id),
 created_at timestamptz default now()
);

create table if not exists public.goals (
 id bigint generated by default as identity primary key,
 team_id bigint not null references public.teams(id),
 title text not null,
 description text default '',
 owner_id bigint references public.users(id),
 target_date text default '',
 status text default 'Planned',
 progress integer default 0,
 created_by bigint references public.users(id),
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);

create table if not exists public.documents (
 id bigint generated by default as identity primary key,
 team_id bigint references public.teams(id),
 title text not null,
 description text default '',
 file_url text not null,
 document_type text default 'Reference',
 created_by bigint references public.users(id),
 created_at timestamptz default now()
);

create table if not exists public.approvals (
 id bigint generated by default as identity primary key,
 team_id bigint references public.teams(id),
 title text not null,
 description text default '',
 approval_type text default 'General',
 requested_by bigint references public.users(id),
 reviewed_by bigint references public.users(id),
 status text default 'Pending',
 review_notes text default '',
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);

create table if not exists public.notifications (
 id bigint generated by default as identity primary key,
 user_id bigint not null references public.users(id) on delete cascade,
 title text not null,
 message text not null,
 kind text default 'info',
 is_read boolean default false,
 created_at timestamptz default now()
);

create table if not exists public.audit_logs (
 id bigint generated by default as identity primary key,
 actor_id bigint references public.users(id),
 action text not null,
 entity_type text not null,
 entity_id bigint,
 details text default '',
 created_at timestamptz default now()
);

create table if not exists public.council_meta (
 key text primary key,
 value text
);

alter table public.tasks add constraint tasks_assigned_to_fkey foreign key (assigned_to) references public.users(id) not valid;
alter table public.tasks add constraint tasks_assigned_by_fkey foreign key (assigned_by) references public.users(id) not valid;
alter table public.tasks add constraint tasks_team_id_fkey foreign key (team_id) references public.teams(id) not valid;

create index if not exists idx_tasks_team_id on public.tasks(team_id);
create index if not exists idx_tasks_assigned_to on public.tasks(assigned_to);
create index if not exists idx_events_team_id on public.events(team_id);
create index if not exists idx_meetings_team_id on public.meetings(team_id);
create index if not exists idx_finances_team_id on public.finances(team_id);
create index if not exists idx_finances_status on public.finances(status);
create index if not exists idx_grievances_status on public.grievances(status);
create index if not exists idx_notifications_user_read on public.notifications(user_id,is_read);
create index if not exists idx_team_members_user on public.team_members(user_id);

alter table public.users enable row level security;
alter table public.teams enable row level security;
alter table public.team_budgets enable row level security;
alter table public.budget_transactions enable row level security;
alter table public.team_members enable row level security;
alter table public.tasks enable row level security;
alter table public.events enable row level security;
alter table public.meetings enable row level security;
alter table public.finances enable row level security;
alter table public.grievances enable row level security;
alter table public.announcements enable row level security;
alter table public.goals enable row level security;
alter table public.documents enable row level security;
alter table public.approvals enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
alter table public.council_meta enable row level security;

-- The current SCMS uses its FastAPI backend for authorization. Direct browser access
-- to these operational tables is therefore denied; the backend connects with a
-- privileged server-side database role. This avoids exposing a service key.
